version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=request
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432